
<div id="page-wrapper">

	<div class="container-fluid">

		<!-- Page Heading -->
		<div class="row">
			<div class="col-lg-12">
				<h1 class="page-header">
					Failed <small>Tests</small>
				</h1>
				<ol class="breadcrumb">
					<li><i class="fa fa-dashboard"></i> <a href="index.html">Dashboard</a></li>
					<li class="active"><i class="fa fa-file"></i>Tests</li>
				</ol>
			</div>
		</div>
		<!-- /.row -->
		<div class="row">
		                    <div class="col-lg-12">
                        <h2>Failed Tests</h2>
                        <div class="table-responsive">
                            <table class="table table-bordered table-hover">
                                <thead>
                                    <tr>
                                        <th>Date/Time</th>
                                        <th>Name</th>
                                        <th>ID</th>
                                        <th>Node ID</th>
                                        <th>Error Code</th>
                                    </tr>
                                </thead>
                                <tbody>
                                        <?php foreach($this->tests as $test) :?><?php print_r ($test)?>
        <tr>
        <td><?php  echo $test->timestamp ?> </td>
        <td><?php echo $test->name ?> </td>
        <td><?php  echo $test->testid ?> </td>
                <td><?php  echo $test->nodeid ?> </td>
                <td><?php  echo $test->error ?> </td>
        
        </tr>
        <?php endforeach;?>

                                </tbody>
                            </table>
                        </div>
                    </div>
        </div>
	</div>
	<!-- /#page-wrapper -->
</div>