
<ol class="breadcrumb">
	<li class="active">
		<i class="fa fa-dashboard"></i> Dashboard
	</li>
</ol>

<div class="row">
	<div class="col-lg-3 col-md-6">
		<div class="panel">
			<div class="panel-heading">
				<div class="row">
					<div class="col-xs-3">
						<i class="fa fa-bar-chart-o fa-5x"></i>
					</div>
					<div class="col-xs-9 text-right">
						<div class="huge"><?php echo $this->count ?></div>
						<div>Tests Active!</div>
					</div>
				</div>
			</div>
			<a href="/tests">
				<div class="panel-footer">
					<span class="pull-left">View Details</span>
					<span class="pull-right"><i class="fa fa-arrow-circle-right"></i></span>
					<div class="clearfix"></div>
				</div>
			</a>
		</div>
	</div>
	<div class="col-lg-3 col-md-6">
		<div class="panel">
			<div class="panel-heading">
				<div class="row">
					<div class="col-xs-3">
						<i class="fa fa-warning fa-5x"></i>
					</div>
					<div class="col-xs-9 text-right">
						<div class="huge"><?php echo $this->failed ?></div>
						<div>Tests Failures!</div>
					</div>
				</div>
			</div>
			<a href="/tests/failed">
				<div class="panel-footer">
					<span class="pull-left">View Details</span>
					<span class="pull-right"><i class="fa fa-arrow-circle-right"></i></span>
					<div class="clearfix"></div>
				</div>
			</a>
		</div>
	</div>
	<div class="col-lg-3 col-md-6">
		<div class="panel">
			<div class="panel-heading">
				<div class="row">
					<div class="col-xs-3">
						<i class="fa fa-database fa-5x"></i>
					</div>
					<div class="col-xs-9 text-right">
						<div class="huge"><?php echo $this->uptime[0]['stotal'] ?></div>
						<div>Tests Performed!</div>
					</div>
				</div>
			</div>
			<a href="#">
				<div class="panel-footer">
					<span class="pull-left">View Details</span>
					<span class="pull-right"><i class="fa fa-arrow-circle-right"></i></span>
					<div class="clearfix"></div>
				</div>
			</a>
		</div>
	</div>
	<div class="col-lg-3 col-md-6">
		<div class="panel">
			<div class="panel-heading">
				<div class="row">
					<div class="col-xs-3">
						<i class="fa fa-cloud fa-5x"></i>
					</div>
					<div class="col-xs-9 text-right">
						<div class="huge"><?php echo $this->nodes[0]['tnodes'] ?></div>
						<div>Nodes Used!</div>
					</div>
				</div>
			</div>
			<a href="/nodes">
				<div class="panel-footer">
					<span class="pull-left">View Details</span>
					<span class="pull-right"><i class="fa fa-arrow-circle-right"></i></span>
					<div class="clearfix"></div>
				</div>
			</a>
		</div>
	</div>
</div>
<!-- /.row -->
<div class="row">
	<div class="col-lg-12">
		<div id="container"></div>
	</div>
</div>
<!-- /.row -->

<script>
$(function () {
	$('#container').highcharts({
		chart: {
			type: 'areaspline',
		},
		title: {
		   text: null
		},
		xAxis: {
			type: 'datetime',
			dateTimeLabelFormats: { // don't display the dummy year
				minute: '%H:%M',
				month: '%e %b',
				year: '%b'
			},
			title: {
				text: 'Date/Time'
			}
		},
		yAxis: {
			labels: {
				format: '{value} ms'
			},
			title: {
				text: 'Total Time'
			},
		},
		tooltip: {
			headerFormat: '<b>{series.name} - {point.x:%e %b}</b><br>',
			pointFormat: '{point.x:%H:%Mhrs}<br><b><span style="font-size:24px">{point.y}ms</span></b>',
		},	
		plotOptions: {
			areaspline: {
				marker: {
					enabled: true,
					symbol: 'circle'
				},
			fillColor: 'rgba(100, 100, 100, 0.1)',
			lineWidth: 2,
			}
		},
		series: <?php echo $this->chartData ?>
	});
});
</script>