<ol class="breadcrumb">
    <li>
        <i class="fa fa-dashboard"></i> <a href="/">Dashboard</a>
    </li>
    <li class="active">
        <i class="fa fa-cloud"></i> Nodes
    </li>
</ol>

<div class="row">
    <div class="col-lg-12">
        <div class="table-responsive">
            <table class="table table-striped table-hover">
                <thead>
                    <tr>
                        <th>ID</th>
                        <th>Node</th>
                        <th>City</th>
                        <th>Carrier</th>
                    </tr>
                </thead>
                <tbody>
                    <?php foreach($this->nodes as $node) :?>
                    <tr>
                        <td><?php  echo $node->id ?> </td>
                        <td><a href="/nodes/index/nodeid/<?php echo $node->id ?>"><?php  echo $node->name ?></a></td>
                        <td><?php echo $node->city ?></td>
                        <td><?php  echo $node->carrier ?> </td>        
                    </tr>
                    <?php endforeach;?>
                </tbody>
            </table>
        </div>
    </div>
</div>
