
<div id="page-wrapper">

	<div class="container-fluid">

		<!-- Page Heading -->
		<div class="row">
			<div class="col-lg-12">
				<h1 class="page-header">
					Nodes
				</h1>
				<ol class="breadcrumb">
					<li><i class="fa fa-dashboard"></i> <a href="/">Dashboard</a></li>
					<li class="active"><i class="fa fa-cloud"></i> Nodes</li>
				</ol>
			</div>
		</div>
		<!-- /.row -->
		<div class="row">
		                    <div class="col-lg-12">
                        <div class="table-responsive">
                            <table class="table table-bordered table-hover">
                                <thead>
                                    <tr>
                                        <th>Node</th>
                                        <th>City</th>
                                        <th>ID</th>
                                    </tr>
                                </thead>
                                <tbody>
                                        <?php foreach($this->nodes as $node) :?>
        <tr>
        <td><a href="/nodes/index/nodeid/<?php echo $node->id ?>"><?php  echo $node->name ?></a></td>
        <td><?php echo $node->city ?></td>
        <td><?php  echo $node->id ?> </td>
        
        </tr>
        <?php endforeach;?>

                                </tbody>
                            </table>
                        </div>
                    </div>
        </div>
	</div>
	<!-- /#page-wrapper -->
</div>