
<div id="page-wrapper">

	<div class="container-fluid">

		<!-- Page Heading -->
		<div class="row">
			<div class="col-lg-12">
				<h1 class="page-header">
					Test <small> Overview</small>
				</h1>
				<ol class="breadcrumb">
					<li><i class="fa fa-dashboard"></i> <a href="/">Dashboard</a></li>
					<li><i class="fa fa-folder"></i> <a href="/index/tests">Tests</a></li>
					<li class="active"><i class="fa fa-bar-chart-o"></i> <?php echo $this->testName?></li>
				</ol>
			</div>
		</div>
		<!-- /.row -->

		<div class="row">
			<div class="col-lg-12">
				<div class="panel panel-default">
					<div class="panel-heading">
						<h3 class="panel-title">
							<i class="fa fa-bar-chart-o fa-fw"></i> <?php echo $this->testName?></h3>
					</div>
					<div class="panel-body">
						<div id="morris-line-chart"></div>
						<div>
						<canvas id="myChart" height="150" width="600"></canvas>
						</div>
					</div>
				</div>
			</div>
		</div>
		<!-- /.row -->

		<div class="row">
			<div class="col-lg-12">
				<div class="panel panel-default">
					<div class="panel-heading">
						<h3 class="panel-title">
							<i class="fa fa-map-marker fa-fw"></i> Node Map
						</h3>
					</div>
					<div class="panel-body">
						<div id="chart_div"></div>
						
					</div>
				</div>
			</div>
		</div>
		<!-- /.row -->

	</div>
	<!-- /.container-fluid -->

</div>

<!-- /#page-wrapper -->
<script>

jQuery(function() {
    // Line Chart
    Morris.Line({
        // ID of the element in which to draw the chart.
        element: 'morris-line-chart',
        // Chart data records -- each entry in this array corresponds to a point on
        // the chart.
        data: <?php echo $this->chartData ?>,
        // The name of the data record attribute that contains x-visitss.
        xkey: 'y',
        // A list of names of data record attributes that contain y-visitss.
        ykeys: <?php echo $this->keys?>,
        // Labels for the ykeys -- will be displayed when you hover over the
        // chart.
        labels: <?php echo $this->keys?>,
        // Disables line smoothing
        smooth: false,
        resize: true
    });
});

</script>

<script>
/*
var options = {

		scaleLabel:' <%=value%> ms',
		responsive: true,
	    scaleShowGridLines : false,
	    bezierCurve : false,

	    //Boolean - Whether to show a stroke for datasets
	    datasetStroke : true,

	    //Number - Pixel width of dataset stroke
	    datasetStrokeWidth : 2,

	    //Boolean - Whether to fill the dataset with a colour
	    datasetFill : true,

	    //String - A legend template
	    legendTemplate : "<ul class=\"<%=name.toLowerCase()%>-legend\"><% for (var i=0; i<datasets.length; i++){%><li><span style=\"background-color:<%=datasets[i].lineColor%>\"></span><%if(datasets[i].label){%><%=datasets[i].label%><%}%></li><%}%></ul>"

	};
var data = {
		labels :<?php echo $this->label?>,
		datasets : [
			{
				label: "<?php echo $this-keys?>",
				fillColor : "rgba(220,220,220,0.2)",
				strokeColor : "rgba(220,220,220,1)",
				pointColor : "rgba(220,220,220,1)",
				pointStrokeColor : "#fff",
				pointHighlightFill : "#fff",
				pointHighlightStroke : "rgba(220,220,220,1)",
	            data: <?php echo $this->chartData ?>
	        }
	    ]
	};
//Get context with jQuery - using jQuery's .get() method.
var ctx = $("#myChart").get(0).getContext("2d");
// This will get the first returned node in the jQuery collection.
var myLineChart = new Chart(ctx).Line(data, options);	
*/
</script>


<script type="text/javascript" src="https://www.google.com/jsapi"></script>
<script>
    google.load('visualization', '1', { 'packages': ['map'] });
    google.setOnLoadCallback(drawMap);

    function drawMap() {
      var data = google.visualization.arrayToDataTable(<?php echo $this->mapData ?>);

    var options = { showTip: true };

    var map = new google.visualization.Map(document.getElementById('chart_div'));

    map.draw(data, options);
  };
  </script>