        <div id="page-wrapper">

            <div class="container-fluid">

                <!-- Page Heading -->
                <div class="row">
                    <div class="col-lg-12">
                        <h1 class="page-header">
                            Test <small> Overview</small>
                        </h1>
                        <ol class="breadcrumb">
					<li><i class="fa fa-dashboard"></i> <a href="/">Dashboard</a></li>
					<li class="active"><i class="fa fa-bar-chart-o"></i> <?php echo $this->testName?></li>
                        </ol>
                    </div>
                </div>
                <!-- /.row -->

                <div class="row">
                    <div class="col-lg-12">
                        <div class="panel panel-default">
                            <div class="panel-heading">
                                <h3 class="panel-title"><i class="fa fa-bar-chart-o fa-fw"></i> <?php echo $this->testName?></h3>
                            </div>
                            <div class="panel-body">
                                <div id="morris-line-chart"></div>
                            </div>
                        </div>
                    </div>
                </div>
                <!-- /.row -->

            </div>
            <!-- /.container-fluid -->

        </div>
        <!-- /#page-wrapper -->
        <script>
jQuery(function() {
    // Line Chart
    Morris.Line({
        // ID of the element in which to draw the chart.
        element: 'morris-line-chart',
        // Chart data records -- each entry in this array corresponds to a point on
        // the chart.
        data: <?php echo $this->chartData ?>,
        // The name of the data record attribute that contains x-visitss.
        xkey: 'y',
        // A list of names of data record attributes that contain y-visitss.
        ykeys: <?php echo $this->keys?>,
        // Labels for the ykeys -- will be displayed when you hover over the
        // chart.
        labels: <?php echo $this->keys?>,
        // Disables line smoothing
        smooth: false,
        resize: true
    });
});
        </script>