
<div id="page-wrapper">

	<div class="container-fluid">

		<!-- Page Heading -->
		<div class="row">
			<div class="page-header">
			<div class="col-lg-12">
				<h1>
					Test <small> Overview</small>
				</h1>
				<ol class="breadcrumb">
					<li><i class="fa fa-dashboard"></i> <a href="/">Dashboard</a></li>
					<li><i class="fa fa-folder"></i> <a href="/index/tests">Tests</a></li>
					<li class="active"><i class="fa fa-bar-chart-o"></i> <?php echo $this->testName?></li>
				</ol>
			</div>
		</div>
	</div>
		<!-- /.row -->

		<div class="row">
			<div class="col-lg-12">
				<div class="panel panel-default">
					<div class="panel-heading">
						<h3 class="panel-title">
							<i class="fa fa-bar-chart-o fa-fw"></i> <?php echo $this->testName?> - Last 7 days</h3>
					</div>
					<div class="panel-body">
						<div id="container"></div>
					</div>
				</div>
			</div>
		</div>
		<!-- /.row -->

		<div class="row">
			<div class="col-lg-12">
				<div class="panel panel-default">
					<div class="panel-heading">
						<h3 class="panel-title">
							<i class="fa fa-map-marker fa-fw"></i> Node Map
						</h3>
					</div>
					<div class="panel-body">
						<div id="mapcontainer"></div>
						
					</div>
				</div>
			</div>
		</div>
		<!-- /.row -->

	</div>
	<!-- /.container-fluid -->

</div>

<!-- /#page-wrapper -->

<script>
$(function () {
    $('#container').highcharts({
        chart: {
            type: 'spline'
        },
        title: {
	       text: null
        },
        xAxis: {
            type: 'datetime',
            dateTimeLabelFormats: { // don't display the dummy year
                minute: '%H:%M',
                month: '%e %b',
                year: '%b'
            },
            title: {
                text: 'Date/Time'
            }
        },
        yAxis: {
            labels: {
                format: '{value} ms'
            },
            title: {
                text: 'Total Time'
            },
            plotLines:[{
                value: 2000,
                color: '#ff0000',
                width: 3,
                label: {
                    text: ''
                }
            }],
            min: 0
        },
        tooltip: {
            headerFormat: '<b>{series.name}</b><br>',
            pointFormat: '{point.x:%e %b %H:%Mhrs}: <b>{point.y}ms</b>'
        },

        plotOptions: {
            spline: {
                marker: {
                    enabled: true,
                    symbol: 'circle'
                }
            }
        },
	series: <?php echo $this->chartData ?>
    });
});


$(function () {
    $('#mapcontainer').highcharts({
        chart: {
            type: 'column'
        },
        title: {
            text: null
        },
        xAxis: {
            crosshair: false,
            labels: {
                enabled: false
            }
        },
        yAxis: {
            min: 0,
            title: {
                text: 'Total Time (ms)'
            }
        },
        tooltip: {
            headerFormat: '<span style="font-size:10px">{point.key}</span><table>',
            pointFormat: '<tr><td style="color:{series.color};padding:0">{series.name}: </td>' +
                '<td style="padding:0"><b>{point.y:.1f} ms</b></td></tr>',
            footerFormat: '</table>',
            shared: true,
            useHTML: true
        },
        plotOptions: {
            column: {
                pointPadding: 0.2,
                borderWidth: 0
            }
        },
        series: <?php echo $this->mapData ?>
    });
});
</script>
<!--
<script type="text/javascript" src="https://www.google.com/jsapi"></script>
<script>
    google.load('visualization', '1', { 'packages': ['map'] });
    google.setOnLoadCallback(drawMap);

    function drawMap() {
      var data = google.visualization.arrayToDataTable(<?php echo $this->mapData ?>);

    var options = { mapType: 'terrain', useMapTypeControl: true, showTip: true };

    var map = new google.visualization.Map(document.getElementById('chart_div'));

    map.draw(data, options);
  };
  </script>
  -->