
<div id="page-wrapper">

	<div class="container-fluid">

		<!-- Page Heading -->
		<div class="row">
			<div class="col-lg-12">
				<h1 class="page-header">
					Test <small>Details</small>
				</h1>
				<ol class="breadcrumb">
					<li><i class="fa fa-dashboard"></i> <a href="index.html">Dashboard</a></li>
					<li class="active"><i class="fa fa-file"></i>Tests</li>
				</ol>
			</div>
		</div>
		<!-- /.row -->
		<div class="row">
		                    <div class="col-lg-12">
                        <h2>Tests</h2>
                        <div class="table-responsive">
                            <table class="table table-bordered table-hover">
                                <thead>
                                    <tr>
                                        <th>Name</th>
                                        <th>Test ID</th>
                                        <th>Type</th>
                                        <th>Monitor</th>
                                    </tr>
                                </thead>
                                <tbody>
                                        <?php foreach($this->tests as $test) :?>
        <tr>
        <td><a href="/index/testdetail/id/<?php echo $test->id ?>"><?php  echo $test->name ?></a></td>
        <td><?php  echo $test->id ?> </td>
                <td><?php  echo $this->type->Types($test->type) ?> </td>
                <td><?php  echo $this->monitor->Monitors($test->monitor) ?> </td>
        
        </tr>
        <?php endforeach;?>

                                </tbody>
                            </table>
                        </div>
                    </div>
        </div>
	</div>
	<!-- /#page-wrapper -->
</div>