
                        <ol class="breadcrumb">
					<li><i class="fa fa-dashboard"></i> <a href="/">Dashboard</a></li>
                        
                            <li class="active"><i class="fa fa-cloud"></i> Node Performance</li>
                        </ol>
                <!-- /.row -->

                <div class="row">
                    <div class="col-lg-12">
                        <div class="panel panel-default">
                            <div class="panel-heading">
                                <h3 class="panel-title"><i class="fa fa-bar-chart-o fa-fw"></i> <?php echo $this->nodeName ?></h3>
                            </div>
                            <div class="panel-body">
                                <div id="morris-bar-chart"></div>
                            </div>
                        </div>
                    </div>
                </div>
                <!-- /.row -->
<script>
//$(document).ready(function() {
    // Line Chart
var chart = Morris.Bar({
        // ID of the element in which to draw the chart.
        element: 'morris-bar-chart',
        // Chart data records -- each entry in this array corresponds to a point on
        // the chart.
        data: <?php echo $this->chartData ?>,
        // The name of the data record attribute that contains x-visitss.
        xkey: 'y',
        // A list of names of data record attributes that contain y-visitss.
        ykeys: <?php echo $this->keys?>,
        // Labels for the ykeys -- will be displayed when you hover over the
        // chart.
        labels: <?php echo $this->keys?>,
        smooth: false,
        postUnits: ' s',
        resize: true
    });
</script>