<ol class="breadcrumb">
    <li>
        <i class="fa fa-dashboard"></i> <a href="/">Dashboard</a>
    </li>
    <li>
        <i class="fa fa-cloud"></i> <a href="/nodes">Nodes</a>
    </li>
    <li class="active">
        <i class="fa fa-chart"></i> Summary
    </li>
</ol>

<div class="row">
    <div class="col-lg-12">
        <div class="panel panel-default">
            <div class="panel-heading">
                <h3 class="panel-title"><i class="fa fa-bar-chart-o fa-fw"></i> <?php echo $this->nodeName ?></h3>
            </div>
            <div class="panel-body">
                <div id="nodecontainer"></div>
            </div>
        </div>
    </div>
</div>

<script>
$(function () {
    $('#nodecontainer').highcharts({
        chart: {
            type: 'column'
        },
        title: {
            text: null
        },
        xAxis: {
            crosshair: false,
            labels: {
                enabled: false
            }
        },
        yAxis: {
            min: 0,
            title: {
                text: 'Total Time (ms)'
            },
            labels: {
                format: '{value} ms'
            }
        },
        tooltip: {
            headerFormat: '<table>',
            pointFormat: '<tr><td style="color:{series.color};padding:0">{series.name}: </td>' +
                '<td style="padding:0"><b>{point.y:.1f} ms</b></td></tr>',
            footerFormat: '</table>',
            shared: true,
            useHTML: true
        },
        plotOptions: {
            column: {
                pointPadding: 0.2,
                borderWidth: 0
            }
        },
        series: <?php echo $this->chartData ?>
    });
});
</script>