<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <meta name="description" content="">
    <meta name="author" content="">
    <title>Catchpoint - Dashboard</title>
    <!-- Bootstrap Core CSS -->
    <link href="/css/bootstrap.min.css" rel="stylesheet">
    <link href="/css/bootstrap-slate.min.css" rel="stylesheet">
    <!-- Custom CSS -->
    <link href="/css/catchpoint.css" rel="stylesheet">
    <!-- Custom Fonts -->
    <link href="/font-awesome-4.1.0/css/font-awesome.min.css" rel="stylesheet" type="text/css">
    <link rel="shortcut icon" href="/images/favicon2.ico">
    <!-- HTML5 Shim and Respond.js IE8 support of HTML5 elements and media queries -->
    <!-- WARNING: Respond.js doesn't work if you view the page via file:// -->
    <!--[if lt IE 9]>
        <script src="https://oss.maxcdn.com/libs/html5shiv/3.7.0/html5shiv.js"></script>
        <script src="https://oss.maxcdn.com/libs/respond.js/1.4.2/respond.min.js"></script>
    <![endif]-->    
    <!-- jQuery Version 1.11.0 -->
    <script src="/js/jquery.min.js"></script>
    <!-- Bootstrap Core JavaScript -->
    <script async src="/js/bootstrap.min.js"></script>
    <!-- HighCharts JavaScript -->
    <script src="http://code.highcharts.com/highcharts.js"></script>
    <script src="/js/dark-unica.js"></script>
</head>
<body>
    <!-- Navigation -->
    <nav class="navbar navbar-default navbar-fixed-top">
    <!-- Brand and toggle get grouped for better mobile display -->
        <div class="container-fluid">
        <div class="navbar-header">
            <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#navbar" aria-expanded="false" aria-controls="navbar">
                <span class="sr-only">Toggle navigation</span>
                <span class="icon-bar"></span>
                <span class="icon-bar"></span>
                <span class="icon-bar"></span>
            </button>
            <a href="/"><img class="img-responsive" src="/images/cp-logo.png" alt="Home"></a>
           
        </div>
        <div id="navbar" class="navbar-collapse collapse">
            <ul class="nav navbar-nav">
                <li><a href="/"><i class="fa fa-fw fa-dashboard"></i> Dashboard</a></li>
                <li><a href="/tests"><i class="fa fa-fw fa-bar-chart-o"></i> Tests</a></li>
                <li><a href="/tests/failed"><i class="fa fa-fw fa-warning"></i> Failures</a></li>
                <li><a href="/nodes"><i class="fa fa-fw fa-cloud"></i> Nodes</a></li>
                <li><a href="/report"><i class="fa fa-fw fa-table"></i> RAG Report</a></li>                         
            </ul>
        </div>
        </div>
    </nav>
    <div class="container-fluid">

        <?php echo $this->layout()->content ?>
        
    </div>
    <script>
    var url = window.location;
    // Will only work if string in href matches with location
    $('ul.nav a[href="' + url + '"]').parent().addClass('active');
    // Will also work for relative and absolute hrefs
    $('ul.nav a').filter(function() {
        return this.href == url;
        }).parent().addClass('active');
    </script>
</body>
</html>